spring:
  cloud:
    stream:
      kafka:
        binder:
          zk-nodes: ${ZK_NODES:zk2001i.bjxy.db.lecloud.com:2001/kafka/kafka9001}
          brokers: ${KAFKA_BROKERS:k9001i.bjxy.db.lecloud.com:9001}
          requiredAcks: -1
          configuration:
            security:
              protocol: SASL_PLAINTEXT
            sasl:
              mechanism: PLAIN
          jaas:
            loginModule: org.apache.kafka.common.security.plain.PlainLoginModule
            options:
              username: tvvideo
              password: tvvideo-secret
    # 开启跟踪事件消息（默认是false）
    bus:
      trace:
        enabled: true
      # 自定义topic主题
      destination: tvvideo.springcloud.config