spring:
  application:
    name: letv-mas-client
  datasource:
    #  配置当前要使用的数据源的操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    #  配置mysql的驱动程序类
    driver-class-name: org.gjt.mm.mysql.Driver
    #  数据库连接地址
    url: jdbc:mysql://m3509i.bjgh.db.lecloud.com:3509/omp?useUnicode=true&characterEncoding=UTF-8
    #  数据库用户名
    username: omp_admin
    #  数据库密码
    password: xu8fZJJg8d9zXZd5
    #  进行数据库连接池的配置
    dbcp2:
      #  数据库连接池的最小维持连接数
      min-idle: 5
      #  初始化提供的连接数
      initial-size: 5
      #  最大连接数
      max-total: 5
      #  等待连接获取的最大超时时间
      max-wait-millis: 200
  redis:
    database: 1
    host: 10.58.89.189
    port: 6379
    password:
    timeout: 2000
    pool:
      max-active: 60
      max-wait: 1000
      max-idle: 5

server:
  port: ${CLIENT_SERVER_PORT:8901}
#  http2:
#    enabled: true

mybatis:
  #  mybatis主配置文件所在路径
  #config-location: classpath:mybatis/mybatis.cfg.xml
  #  定义所有操作类的别名所在包
  type-aliases-package: com.letv.mas.client.demo.model.dto
  #  所有的mapper映射文件
  mapperLocations: com.letv.mas.mapper/*.xml