eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/

server:
  port: 8764

spring:
  application:
    name: service-consumer-ribbon
  zipkin:
    base-url: http://localhost:9001
  sleuth:
    sampler:
      percentage: 1.0

info:
  app:
    name: "@project.artifactId@"
    encoding: '@project.build.sourceEncoding@'
    java:
      source: '@java.version@'
      target: '@java.version@'