jedis:
  redis:
    master:
      ip: 10.58.89.189
      port: 6379
      socket-timeout: 2000
    slave:
      ip: 10.58.89.189
      port: 6379
      socket-timeout: 2000
    pool:
      max-active: 60
      max-wait: 1000
      max-idle: 5
      test-on-borrow: false
      test-on-return: true