spring:
  metrics:
    servo:
      enabled: false
#    export:
#      enabled: true
#      influx:
#        uri: http://10.58.89.189:8086
#        username: api
#        password: api@20180307
#        db: letv-mas
#        batchCount: 10
#        batchInterval: 1000
#      delay-millis: 5000
#      includes: heap.used,heap.committed,mem,mem.free,threads,datasource.primary.active,datasource.primary.usage

management:
  metrics:
    export:
      enabled: true
      influx:
        enabled: true
        auto-create-db: true
        batch-size: 10000
        compressed: true
        connect-timeout: 1s
        consistency: one
        uri: ${METRICS_INFLUXDB_URI:http://10.58.89.189:8086}
        db: ${METRICS_INFLUXDB_DB:letv-mas-service}
        num-threads: 2
        user-name: ${METRICS_INFLUXDB_USERNAME:api}
        password: ${METRICS_INFLUXDB_PASSWORD:api@20180307}
        read-timeout: 2s
        retention-policy:
        step: PT10s