spring:
  # 默认Lettuce客户端（可选jedis，pom依赖参考注释部分），基于Netty多线程并发，伸缩式动态扩展连接！
  redis:
    # 用于Connection Factory的数据库索引
    database: 1
    host: ${REDIS_M_HOST:10.58.89.189}
    port: ${REDIS_M_PORT:6379}
    # 连接超时时间 单位 ms（毫秒）
    timeout: 3000
    pool:
      # 连接池中的最大空闲连接，默认值8
      max-idle: 8
      # 连接池中的最小空闲连接，默认值0
      min-idle: 0
      # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
      max-active: 50
      # 等待可用连接的最大时间 单位 ms（毫秒），默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
      max-wait: 1000
    # redis哨兵主从设置
#    sentinel:
      # master服务器的名字
#      master: master1
      # redis-sentinel的配置地址和端口
#      nodes: 127.0.0.1:26377,127.0.0.1:26378,127.0.0.1:26379
