eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/

server:
  port: 8101

spring:
  application:
    name: service-router-zuul
  zipkin:
    base-url: http://localhost:9001
  sleuth:
    sampler:
      percentage: 1.0
  cloud:
    config:
      # uri: http://localhost:8021/
      discovery:
        enabled: true #启用发现服务功能
        service-id: config-server #指定服务名称
      name: service-router-zuul
      label: master
      profile: dev
zuul:
  routes:
    api-1:
      path: /api-1/**
      serviceId: service-consumer-ribbon

info:
  app:
    name: "@project.artifactId@"
    encoding: '@project.build.sourceEncoding@'
    java:
      source: '@java.version@'
      target: '@java.version@'