eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${ROUTER_SERVER_IP}
    instance-id: ${spring.application.name}:${server.port}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_LIST}
    healthcheck:
      enabled: true

server:
  port: ${ROUTER_SERVER_PORT}

spring:
  application:
    name: letv-mas-router
  zipkin:
    #base-url: http://localhost:9001
    base-url: ${TRACE_SERVER_URL}
  sleuth:
    sampler:
      percentage: 1.0
  cloud:
    config:
      #failFast: true #the client will halt with an Exception
      # uri: http://localhost:8021/
      discovery:
        enabled: true #启用发现服务功能
        service-id: letv-mas-config #指定服务名称
      # eg. http://localhost:8021/{name}/{profile}/{label}
      name: letv-mas-router
      label: master
      profile: dev
zuul:
  routes:
    api-1:
      path: /api-1/**
      serviceId: letv-mas-caller

info:
  app:
    name: "@project.artifactId@"
    encoding: '@project.build.sourceEncoding@'
    java:
      source: '@java.version@'
      target: '@java.version@'