spring:
  application:
    name: letv-mas-router-tvproxy
    index: ${ROUTER_SERVER_IP}:${ROUTER_SERVER_PORT}
  cloud:
    loadbalancer:
      retry:
        enabled: true
  profiles:
    include: config,zuul,trace
  metrics:
    servo:
      enabled: false
#    export:
#      enabled: true
#      influx:
#        uri: http://10.58.89.189:8086
#        username: api
#        password: api@20180307
#        db: letv-mas
#        batchCount: 10
#        batchInterval: 1000
#      delay-millis: 5000
#      includes: heap.used,heap.committed,mem,mem.free,threads,datasource.primary.active,datasource.primary.usage

server:
  port: ${ROUTER_SERVER_PORT}
  tomcat: 
    accept-count: 1000 
    max-threads: 1000
    max-connections: 1000

security:
  basic:
    # 启用基本身份认证
    enabled: false
  user:
    name: letvMasRouter
    password: admin20180806
    role: USER

management:
  security:
    enabled: false
# /info 显示全部git版控相关信息
#  info:
#    git:
#      mode: full
  metrics:
    export:
      enabled: true
      influx:
        enabled: true
        auto-create-db: true
        batch-size: 10000
        compressed: true
        connect-timeout: 1s
        consistency: one
        uri: http://10.58.89.189:8086
        db: letv-mas-service
        num-threads: 2
        user-name: api
        password: api@20180307
        read-timeout: 2s
        retention-policy:
        step: PT10s

eureka:
  instance:
    # 全网服务实例唯一标识
    instance-id: ${ROUTER_SERVER_IP:127.0.0.1}:${server.port}
    # 服务实例的meta数据键值对集合，可由注册中心进行服务实例间传递
    metadata-map:
      # [HA-P配置]-当前服务实例的zone
      zone: ${ROUTER_SERVER_ZONE:sjs-1}
      #config bus refresh index
      index: ${spring.application.index:127.0.0.1}
      #config bus refresh profiles
      profiles: ${spring.profiles.include},${spring.profiles.active}
    # 开启ip，默认为false＝》hostname
    prefer-ip-address: true
    ip-address: ${ROUTER_SERVER_IP:127.0.0.1}
    # [服务续约]-心跳检查之服务失效时间，默认为90s，这个配置一般为lease-renewal-interval-in-seconds的三倍！eureka server bug,失效为2倍时间，故设置1/2
    lease-expiration-duration-in-seconds: 15
    # [服务续约]-服务续约任务调用的间隔时间，默认为30s
    lease-renewal-interval-in-seconds: 10
    # [服务监控]-当前实例的服务信息地址
    status-page-url: http://${ROUTER_SERVER_IP:127.0.0.1}:${server.port}/info
    # [服务监控]-当前实例的服务健康状态地址
    health-check-url: http://${ROUTER_SERVER_IP:127.0.0.1}:${server.port}/health
  client:
    # [HA-P配置]-当前服务实例的region
    region: ${ROUTER_SERVER_REGION:cn-bj}
    # [HA-P配置]-开启当前服务实例优先发现同zone的注册中心，默认为true
    prefer-same-zone-eureka: true
    # [服务注册]-允许当前服务实例注册，默认为true
    register-with-eureka: true
    # [服务续约]-允许当前服务实例获取注册信息，默认为true
    fetch-registry: true
    # [HA配置]-可用zone内注册中心地址列表
    availability-zones:
      cn-bj: ${eureka.instance.metadata-map.zone},sjs-1,dx-1
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      # [HA配置]-默认zone内注册中心地址列表
      #testDefaultZone: ${EUREKA_SERVER_LIST:http://letvMasManager:admin20180605@10.112.34.124:8015/eureka}
      sjs-1: http://letvMasManager:admin20180605@10.129.29.86:8015/eureka,http://letvMasManager:admin20180605@10.129.29.90:8015/eureka
      dx-1: http://letvMasManager:admin20180605@10.112.34.124:8015/eureka,http://letvMasManager:admin20180605@10.112.34.127:8015/eureka
      defaultZone: ''
    # [服务续约]-当前服务实例更新注册服务缓存清单的更新间隔时间，默认为30s，一般和lease-renewal-interval-in-seconds保持一致！
    registry-fetch-interval-seconds: 10
    # [服务监控]-开启健康检查，只能在application.yml中设置！
    healthcheck:
      enabled: true
    # 注册时会try3个注册地址，3 不能改变，均失败后，后台定时会继续注册，retryableClientQuarantineRefreshPercentage源码为0.66，这个是尝试注册的比例。
    # 调整为1，继续注册时会跳过之前注册失败的地址。
    # 详见源码RetryableEurekaHttpClient.getHostCandidates
    transport:
      retryable-client-quarantine-refresh-percentage: 1

endpoints:
  refresh:
    enabled: true
    # 安全验证
    sensitive: false
  shutdown:
    # curl -d "" http://letvMasRouter:admin20180806@127.0.0.1:9000/shutdown
    enabled: true
    # 安全验证
    sensitive: true

# 自定义系统日志输出
logout:
  path: /letv/logs/mas/router
  level: INFO
  capacity: 30GB
