eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${ROUTER_SERVER_IP}
    instance-id: ${spring.application.name}:${server.port}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_LIST}
    healthcheck:
      enabled: true

spring:
  application:
    name: letv-mas-router
  zipkin:
    #base-url: http://localhost:9001
    base-url: ${TRACE_SERVER_URL}
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: ${ROUTER_SERVER_PORT}

zuul:
  routes:
    api-1:
      path: /api-1/**
      serviceId: letv-mas-caller

management:
  security:
    enabled: false

info:
  app:
    name: "@project.artifactId@"
    encoding: '@project.build.sourceEncoding@'
    java:
      source: '@java.version@'
      target: '@java.version@'
