spring:
  mvc:
    favicon:
      enabled: false
  http:
    converters:
      preferred-json-mapper: fastjson
    encoding:
      force: true
  application:
    #name: letv-mas-caller-tvproxy
    index: ${SERVER_IP:127.0.0.1}:${CALLER_SERVER_PORT:5555}
  #profiles:
    #include: app,redis,db,hystrix,stream,manager,omp,trace,thrift
  zipkin:
      enabled: false
#  metrics:
#    servo:
#      enabled: false
  sleuth:
      enabled: false
  scheduled:
        enabled: false
  cloud:
    bus:
      enabled: false
    eureka:
      client:
        enabled: false
    iptv:
      enabled: true
      doc:
        enabled: false
      host-log:
        enabled: true
      hystrix-log:
        enabled: true
server:
  port: ${SERVER_PORT:5555}
  #servlet-path: /iptv/api/new
  #context-path: /iptv/api/new
  #path: '/iptv/api/new'
  tomcat:
    accept-count: 1000
    max-threads: 1000
    max-connections: 1000

endpoints:
  refresh:
    enabled: true
    # 安全验证
    sensitive: false
  shutdown:
    enabled: true
    # 安全验证
    sensitive: false

management:
  security:
    enabled: false
  health:
    redis:
      enabled: false

security:
  basic:
    # 启用基本身份认证
    enabled: false

# 自定义系统日志输出
logout:
  path: /letv/logs/mas/caller/tvproxy
  level: 'info'
  capacity: 30GB
logging:
  level:
    root: info
    org.apache.kafka: info
    org.apache.kafka.clients: info
    org.apache.kafka.common: info

jasypt:
  encryptor:
    password: LetvMas@201811