hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: '20'
        sleepWindowInMilliseconds: '5000'
        errorThresholdPercentage: '50'
      metrics:
        rollingStats:
          timeInMilliseconds: '10000'
          numBuckets: '10'
        rollingPercentile:
          enabled: 'false'
          timeInMilliseconds: '10000'
          numBuckets: '10'
          bucketSize: '100'
      execution:
        isolation:
          strategy: 'THREAD'
          thread:
            timeoutInMilliseconds: 1000
            interruptOnTimeout: 'true'
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 1000
      requestCache:
        enabled: false
      requestLog:
        enabled: false
  threadpool:
    default:
      # 核心线程数量
      coreSize: 100
      # 最大线程数量
      maximumSize: 100
      # 当设为-1，会使用SynchronousQueue; 值为正则使用LinkedBlcokingQueue；该设置只会在初始化时有效，之后不能修改
      maxQueueSize: -1