jedis:
  redis:
    master:
      ip: ${REDIS_M_IP:10.58.89.189}
      port: ${REDIS_M_PORT:6379}
      socket-timeout: 2000
    slave:
      ip: ${REDIS_S_IP:10.58.89.189}
      port: ${REDIS_S_PORT:6379}
      socket-timeout: 2000
    pool:
      max-active: 60
      max-wait: 1000
      max-idle: 5
      test-on-borrow: false
      test-on-return: true