spring:
  application:
    name: letv-mas-client
  zipkin:
    base-url: ${TRACE_SERVER_URL:http://127.0.0.1:9001}
    enabled: false
  sleuth:
    sampler:
      percentage: 1.0
    enabled: false
    scheduled:
      enabled: false
  cloud:
    bus:
      enabled: false
  datasource:
    #  配置当前要使用的数据源的操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    #  配置mysql的驱动程序类
    driver-class-name: org.gjt.mm.mysql.Driver
    #  数据库连接地址
    url: jdbc:mysql://10.58.92.90:3306/letv?useUnicode=true&characterEncoding=UTF-8
    #  数据库用户名
    username: zhangshuai6
    #  数据库密码
    password: zhangshuai6@le.com
    #  进行数据库连接池的配置
    dbcp2:
      #  数据库连接池的最小维持连接数
      min-idle: 5
      #  初始化提供的连接数
      initial-size: 5
      #  最大连接数
      max-total: 5
      #  等待连接获取的最大超时时间
      max-wait-millis: 200
  redis:
    database: 1
    host: 10.58.92.90
    port: 6379
    password: 123456
    timeout: 5000

server:
  port: ${CLIENT_SERVER_PORT:8901}
#  http2:
#    enabled: true

eureka:
  instance:
    # 全网服务实例唯一标识
    instance-id: ${CLIENT_SERVER_IP:127.0.0.1}:${server.port}
    # 服务实例的meta数据键值对集合，可由注册中心进行服务实例间传递
    metadata-map:
      # [HA-P配置]-当前服务实例的zone
      zone: ${EUREKA_SERVER_ZONE:tz-1}
    # 开启ip，默认为false＝》hostname
    prefer-ip-address: true
    ip-address: ${CLIENT_SERVER_IP:127.0.0.1}
    # [服务续约]-心跳检查之服务失效时间，默认为90s，这个配置一般为lease-renewal-interval-in-seconds的三倍！
    lease-expiration-duration-in-seconds: 30
    # [服务续约]-服务续约任务调用的间隔时间，默认为30s
    lease-renewal-interval-in-seconds: 10
    # [服务监控]-当前实例的服务信息地址
    status-page-url: http://${CLIENT_SERVER_IP:127.0.0.1}:${server.port}/info
    # [服务监控]-当前实例的服务健康状态地址
    health-check-url: http://${CLIENT_SERVER_IP:127.0.0.1}:${server.port}/health
  client:
    # [HA-P配置]-当前服务实例的region
    region: ${EUREKA_SERVER_REGION:cn-bj}
    # [HA-P配置]-开启当前服务实例优先发现同zone的注册中心，默认为true
    prefer-same-zone-eureka: true
    # [服务注册]-允许当前服务实例注册，默认为true
    register-with-eureka: true
    # [服务续约]-允许当前服务实例获取注册信息，默认为true
    fetch-registry: true
    # [HA配置]-可用zone内注册中心地址列表
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      # [HA配置]-默认zone内注册中心地址列表
      defaultZone: ${EUREKA_SERVER_LIST:http://127.0.0.1:8011/eureka}
    # [服务续约]-当前服务实例更新注册服务缓存清单的更新间隔时间，默认为30s，一般和lease-renewal-interval-in-seconds保持一致！
    registry-fetch-interval-seconds: 10
    # [服务监控]-开启健康检查，只能在application.yml中设置！
    healthcheck:
      enabled: true

info:
  app:
    name: "@project.artifactId@"
    encoding: '@project.build.sourceEncoding@'
    java:
      source: '@java.version@'
      target: '@java.version@'

management:
  security:
    enabled: false


mybatis:
  #  mybatis主配置文件所在路径
  #config-location: classpath:mybatis/mybatis.cfg.xml
  #  定义所有操作类的别名所在包
  type-aliases-package: com.letv.mas.client.demo.model.dto
  #  所有的mapper映射文件
  mapperLocations: com.letv.mas.mapper/*.xml