spring:
  application:
    name: eureka-server-test-client
  zipkin:
      enabled: false
  sleuth:
      enabled: false
  scheduled:
        enabled: false
  cloud:
    bus:
      enabled: false
    eureka:
      client:
        enabled: true
server:
  port: 9992
eureka:
  instance:
    # 全网服务实例唯一标识
    instance-id: ${eureka.instance.ip-address}:${server.port}
    # 服务实例的meta数据键值对集合，可由注册中心进行服务实例间传递
    metadata-map:
      # [HA-P配置]-当前服务实例的zone
      zone: dx-1
    # 开启ip，默认为false＝》hostname
    prefer-ip-address: true
    ip-address: 127.0.0.1
    # [服务续约]-心跳检查之服务失效时间，默认为90s，这个配置一般为lease-renewal-interval-in-seconds的三倍！
    lease-expiration-duration-in-seconds: 15
    # [服务续约]-服务续约任务调用的间隔时间，默认为30s
    lease-renewal-interval-in-seconds: 10
    # [服务监控]-当前实例的服务信息地址
    status-page-url: http://${CLIENT_SERVER_IP:127.0.0.1}:${server.port}/info
    # [服务监控]-当前实例的服务健康状态地址
    health-check-url: http://${CLIENT_SERVER_IP:127.0.0.1}:${server.port}/health
  client:
    # [HA-P配置]-开启当前服务实例优先发现同zone的注册中心，默认为true
    prefer-same-zone-eureka: true
    # [服务注册]-允许当前服务实例注册，默认为true
    register-with-eureka: true
    # [服务续约]-允许当前服务实例获取注册信息，默认为true
    fetch-registry: true
    # [HA配置]-可用zone内注册中心地址列表
    region: cn_bj
    availability-zones:
      cn_bj: ${eureka.instance.metadata-map.zone},sjs-1,dx-1
    service-url:
      sjs-1: http://letvMasManager:admin20180605@10.129.29.90:8015/eureka
      dx-1: http://letvMasManager:admin20180605@10.112.34.124:8015/eureka
      #sjs-1: http://letvMasManager:admin20180605@10.129.29.86:8015/eureka,http://letvMasManager:admin20180605@10.129.29.90:8015/eureka
      #dx-1: http://letvMasManager:admin20180605@10.112.34.124:8015/eureka,http://letvMasManager:admin20180605@10.112.34.127:8015/eureka
      #defaultZone: ''
    # [服务续约]-当前服务实例更新注册服务缓存清单的更新间隔时间，默认为30s，一般和lease-renewal-interval-in-seconds保持一致！
    registry-fetch-interval-seconds: 10
    # [服务监控]-开启健康检查，只能在application.yml中设置！
    healthcheck:
      enabled: true
endpoints:
  refresh:
    enabled: true
    # 安全验证
    sensitive: false
  shutdown:
    enabled: true
    # 安全验证
    sensitive: false